# Site Settings
title: Blog Diohananto
email: dionrangga98@gmail.com
description: >
  A guide to getting started with Jekyll.
baseurl: "/blog"
url: "http://diohananto.github.io"
twitter_username: diohananto
github_username:  diohananto
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
